
"""Zero-cost, multi-stage AI-media screening for SamiBOT."""

from __future__ import annotations
import asyncio
import io
import json
import os
import subprocess
import tempfile
import time
import wave
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import numpy as np
from ai_media_onnx import local_onnx_image, local_onnx_audio
from PIL import Image, ExifTags

try:
    import cv2
except Exception:
    cv2 = None

try:
    from scipy import signal as scipy_signal
except Exception:
    scipy_signal = None

try:
    from huggingface_hub import AsyncInferenceClient
except Exception:
    AsyncInferenceClient = None

try:
    import c2pa
except Exception:
    c2pa = None

try:
    import imageio_ffmpeg
except Exception:
    imageio_ffmpeg = None

MAX_BYTES = int(os.getenv("AI_DETECT_MAX_BYTES", str(15 * 1024 * 1024)))
LOW = float(os.getenv("AI_DETECT_BORDERLINE_LOW", "35"))
HIGH = float(os.getenv("AI_DETECT_BORDERLINE_HIGH", "65"))
HF_TIMEOUT = float(os.getenv("AI_DETECT_HF_TIMEOUT", "20"))
HF_COOLDOWN = float(os.getenv("AI_DETECT_HF_COOLDOWN", "30"))
DEFAULT_IMAGE_MODEL = os.getenv(
    "HF_IMAGE_MODEL",
    "Minachist/ai-illust-detector-siglip2-so400m-patch16-384",
)
DEFAULT_AUDIO_MODEL = os.getenv(
    "HF_AUDIO_MODEL",
    "koyelog/deepfake-voice-detector-sota",
)

GENERATOR_SIGNATURES = {
    "Midjourney": ("midjourney", "midjourney ai"),
    "OpenAI/DALL-E": ("dall-e", "dall·e", "dall e", "openai"),
    "Stable Diffusion": (
        "stable diffusion", "stability ai", "stablediffusion",
        "automatic1111", "comfyui", "fooocus",
    ),
    "Adobe Firefly": ("firefly", "adobe firefly"),
    "Google Imagen": ("google imagen", "imagen 2", "imagen 3", "imagen 4"),
    "ElevenLabs": ("elevenlabs", "eleven labs"),
    "Suno": ("suno ai", "suno.com"),
    "Udio": ("udio ai", "udio.com"),
}
AI_ASSERTION_TERMS = (
    "c2pa.ai-disclosure", "ai-disclosure", "generated by ai",
    "ai-generated", "ai generated", "generative",
)

@dataclass
class Evidence:
    source: str
    message: str
    weight: float
    score: Optional[float] = None

@dataclass
class DetectionResult:
    media_type: str
    ai_likelihood: float = 50.0
    confidence: str = "low"
    decision: str = "uncertain"
    evidence: list[Evidence] = field(default_factory=list)
    stages: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    remote_used: bool = False
    elapsed_ms: int = 0

class DetectorError(Exception):
    pass

def _clamp(x, lo=0.0, hi=100.0):
    return max(lo, min(hi, float(x)))

def _raw_text(data):
    return data[:2000000].decode("utf-8", errors="ignore").casefold()

def _generator_evidence(text):
    out = []
    for vendor, terms in GENERATOR_SIGNATURES.items():
        if any(term in text for term in terms):
            out.append(Evidence(
                "metadata",
                "Generator signature found: %s." % vendor,
                100,
                100,
            ))
    return out

def _manifest_evidence(obj):
    text = json.dumps(obj, ensure_ascii=False).casefold()
    out = []
    for term in AI_ASSERTION_TERMS:
        if term in text:
            out.append(Evidence(
                "c2pa",
                "C2PA manifest contains an AI/generative disclosure: %s." % term,
                95,
                98,
            ))
    for vendor, terms in GENERATOR_SIGNATURES.items():
        if any(term in text for term in terms):
            out.append(Evidence(
                "c2pa",
                "C2PA manifest references %s." % vendor,
                95,
                98,
            ))
    if "validation_status" in text and ("error" in text or "invalid" in text):
        out.append(Evidence(
            "c2pa",
            "C2PA data was present but validation reported an error.",
            20,
            55,
        ))
    return out

def inspect_metadata(data, filename="media"):
    evidence = _generator_evidence(_raw_text(data))
    lower = data[:2000000].lower()

    if b"c2pa" in lower:
        evidence.append(Evidence(
            "c2pa",
            "C2PA/Content Credentials marker detected.",
            70,
            50,
        ))
    if b"cabx" in lower or b"jumb" in lower:
        evidence.append(Evidence(
            "c2pa",
            "Possible C2PA JUMBF/caBX container detected.",
            70,
            50,
        ))

    try:
        with Image.open(io.BytesIO(data)) as im:
            if im.info:
                info_text = " ".join(
                    str(k) + "=" + str(v)[:1000] for k, v in im.info.items()
                ).casefold()
                evidence.extend(_generator_evidence(info_text))
                evidence.append(Evidence(
                    "metadata",
                    "Embedded image metadata fields found: %s."
                    % ", ".join(str(k) for k in list(im.info)[:8]),
                    5,
                    50,
                ))
            try:
                exif = im.getexif()
                exif_text = " ".join(
                    str(ExifTags.TAGS.get(k, k)) + "=" + str(v)
                    for k, v in exif.items()
                ).casefold()
                evidence.extend(_generator_evidence(exif_text))
            except Exception:
                pass
    except Exception:
        pass

    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        if b"caBX" in data[:4000000]:
            evidence.append(Evidence(
                "c2pa",
                "PNG caBX C2PA chunk detected.",
                70,
                70,
            ))
        for marker in (b"tEXt", b"iTXt", b"zTXt"):
            if marker in data[:4000000]:
                evidence.append(Evidence(
                    "metadata",
                    "PNG textual chunk detected: %s." % marker.decode(errors="ignore"),
                    5,
                    50,
                ))

    if c2pa is not None and (
        b"c2pa" in lower or b"cabx" in lower or b"jumb" in lower
    ):
        tmp = None
        try:
            suffix = Path(filename).suffix or ".bin"
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as fh:
                fh.write(data)
                tmp = fh.name
            with c2pa.Reader(tmp) as reader:
                manifest = json.loads(reader.json())
            evidence.extend(_manifest_evidence(manifest))
            evidence.append(Evidence(
                "c2pa",
                "C2PA manifest was parsed by the native C2PA Reader.",
                90,
                60,
            ))
        except Exception as exc:
            evidence.append(Evidence(
                "c2pa",
                "C2PA marker exists, but validation/read failed: %s."
                % type(exc).__name__,
                20,
                50,
            ))
        finally:
            if tmp:
                try:
                    os.unlink(tmp)
                except OSError:
                    pass

    strong = any(
        e.source in ("metadata", "c2pa") and e.score is not None and e.score >= 95
        for e in evidence
    )
    return evidence, strong

def _entropy(gray):
    if cv2 is not None:
        hist = cv2.calcHist([gray], [0], None, [256], [0, 256]).ravel()
    else:
        hist = np.histogram(gray, bins=256, range=(0, 256))[0]
    p = hist / max(float(hist.sum()), 1.0)
    p = p[p > 0]
    return float(-(p * np.log2(p)).sum())

def image_heuristics(data):
    if cv2 is None:
        return 50.0, [Evidence("local", "OpenCV unavailable; image heuristics skipped.", 0, 50)]
    with Image.open(io.BytesIO(data)) as pil:
        pil = pil.convert("RGB")
        if max(pil.size) > 1800:
            pil.thumbnail((1800, 1800), Image.Resampling.LANCZOS)
        arr = np.asarray(pil)
    gray = cv2.cvtColor(arr, cv2.COLOR_RGB2GRAY).astype(np.float32)
    lap = float(cv2.Laplacian(gray, cv2.CV_64F).var())
    ent = _entropy(gray)
    fft = np.fft.fftshift(np.fft.fft2(gray))
    power = np.abs(fft) ** 2
    h, w = power.shape
    yy, xx = np.ogrid[:h, :w]
    radius = np.sqrt((yy - h / 2) ** 2 + (xx - w / 2) ** 2)
    high = float(power[radius > min(h, w) * 0.28].mean())
    low = float(power[radius <= min(h, w) * 0.12].mean()) + 1e-9
    ratio = high / low
    score = 50.0
    evidence = []

    if lap < 45:
        score += 4
        evidence.append(Evidence(
            "local", "Low Laplacian edge variance (%.1f)." % lap, 4, 54
        ))
    elif lap > 900:
        score -= 3
        evidence.append(Evidence(
            "local", "High Laplacian edge variance (%.1f)." % lap, 3, 47
        ))
    if 0.001 < ratio < 0.06:
        score += 4
        evidence.append(Evidence(
            "local", "Unusual FFT high/low-frequency ratio (%.4f)." % ratio, 4, 54
        ))
    if ent < 5.0:
        score += 2
        evidence.append(Evidence(
            "local", "Low grayscale entropy (%.2f bits)." % ent, 2, 52
        ))
    elif ent > 7.5:
        score -= 2
        evidence.append(Evidence(
            "local", "High grayscale entropy (%.2f bits)." % ent, 2, 48
        ))
    return _clamp(score), evidence

def _decode_audio(data):
    if data[:4] == b"RIFF" and data[8:12] == b"WAVE":
        return data
    if imageio_ffmpeg is None:
        raise DetectorError("ffmpeg decoder is unavailable for this audio format")
    exe = imageio_ffmpeg.get_ffmpeg_exe()
    proc = subprocess.run(
        [
            exe, "-hide_banner", "-loglevel", "error", "-i", "pipe:0",
            "-ac", "1", "-ar", "16000", "-f", "wav", "pipe:1"
        ],
        input=data,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=20,
        check=False,
    )
    if proc.returncode != 0 or not proc.stdout.startswith(b"RIFF"):
        raise DetectorError("audio could not be decoded")
    return proc.stdout

def _read_wav(wav_bytes):
    with wave.open(io.BytesIO(wav_bytes), "rb") as wf:
        sr = wf.getframerate()
        channels = wf.getnchannels()
        width = wf.getsampwidth()
        frames = wf.readframes(min(wf.getnframes(), sr * 120))
    if width == 1:
        x = (np.frombuffer(frames, dtype=np.uint8).astype(np.float32) - 128) / 128
    elif width == 2:
        x = np.frombuffer(frames, dtype=np.int16).astype(np.float32) / 32768
    elif width == 4:
        x = np.frombuffer(frames, dtype=np.int32).astype(np.float32) / 2147483648
    else:
        raise DetectorError("unsupported PCM sample width")
    if channels > 1:
        x = x.reshape(-1, channels).mean(axis=1)
    return x, sr

def audio_heuristics(data):
    wav = _decode_audio(data)
    x, sr = _read_wav(wav)
    if len(x) < max(1600, sr // 4):
        raise DetectorError("voice clip is too short for signal analysis")
    x = x - float(np.mean(x))
    x = x / (float(np.max(np.abs(x))) + 1e-9)
    frame = max(160, int(sr * 0.025))
    hop = max(80, int(sr * 0.010))

    if scipy_signal is not None:
        _, _, z = scipy_signal.stft(
            x, fs=sr, nperseg=frame, noverlap=frame-hop, boundary=None
        )
        mag = np.abs(z) + 1e-9
    else:
        rows = []
        for start in range(0, len(x) - frame, hop):
            win = x[start:start + frame] * np.hanning(frame)
            rows.append(np.abs(np.fft.rfft(win)) + 1e-9)
        mag = np.asarray(rows).T if rows else np.empty((1, 1))

    flatness = np.exp(np.mean(np.log(mag), axis=0)) / np.mean(mag, axis=0)
    rms = np.sqrt(
        np.convolve(x * x, np.ones(frame) / frame, mode="valid")
    )
    silence = float(np.mean(rms < 0.025))
    flat = float(np.median(flatness))
    score = 50.0
    evidence = []

    if flat < 0.08:
        score += 5
        evidence.append(Evidence(
            "local", "Very low median spectral flatness (%.3f)." % flat, 5, 55
        ))
    elif flat > 0.35:
        score -= 3
        evidence.append(Evidence(
            "local", "Higher spectral flatness (%.3f)." % flat, 3, 47
        ))
    if 0.08 < silence < 0.32:
        score += 2
        evidence.append(Evidence(
            "local", "Regular speech-like silence ratio (%.1f%%)." % (silence * 100),
            2, 52
        ))
    evidence.append(Evidence(
        "local", "Decoded mono audio: %.1fs @ %d Hz." % (len(x) / sr, sr), 0, 50
    ))
    return _clamp(score), evidence, wav

def _remote_score(label, score):
    text = label.casefold().replace("-", "_").replace(" ", "_")
    if any(k in text for k in ("ai", "fake", "deepfake", "synthetic", "generated", "spoof")):
        return score * 100
    if any(k in text for k in ("real", "human", "authentic", "bonafide", "natural")):
        return (1.0 - score) * 100
    return None

_hf_last_call = 0.0

async def _hf_client():
    global _hf_last_call
    token = os.getenv("HF_TOKEN", "").strip()
    if not token or AsyncInferenceClient is None:
        return None
    wait = HF_COOLDOWN - (time.monotonic() - _hf_last_call)
    if wait > 0:
        await asyncio.sleep(wait)
    _hf_last_call = time.monotonic()
    return AsyncInferenceClient(
        provider="hf-inference",
        token=token,
        timeout=HF_TIMEOUT,
    )

async def remote_image(data):
    client = await _hf_client()
    if client is None:
        return None
    model = DEFAULT_IMAGE_MODEL
    try:
        outputs = await client.image_classification(data, model=model, top_k=8)
        candidates = []
        for item in outputs:
            s = _remote_score(str(item.label), float(item.score))
            if s is not None:
                candidates.append((s, str(item.label), float(item.score)))
        if not candidates:
            return None
        candidates.sort(key=lambda item: abs(item[0] - 50), reverse=True)
        score, label, raw = candidates[0]
        return _clamp(score), "HF image model %s: %s (%.1f%%)." % (
            model, label, raw * 100
        )
    except Exception:
        return None

async def remote_audio(data):
    client = await _hf_client()
    if client is None:
        return None
    model = DEFAULT_AUDIO_MODEL
    try:
        outputs = await client.audio_classification(data, model=model, top_k=8)
        candidates = []
        for item in outputs:
            s = _remote_score(str(item.label), float(item.score))
            if s is not None:
                candidates.append((s, str(item.label), float(item.score)))
        if not candidates:
            return None
        candidates.sort(key=lambda item: abs(item[0] - 50), reverse=True)
        score, label, raw = candidates[0]
        return _clamp(score), "HF audio model %s: %s (%.1f%%)." % (
            model, label, raw * 100
        )
    except Exception:
        return None

def _fuse(local, detector=None):
    # Local signal heuristics remain weak evidence. A real detector model gets
    # more weight, but the final score is still pulled toward uncertainty.
    score = 50.0 * 0.35 + local * 0.65
    if detector is not None:
        score = score * 0.35 + detector * 0.65
    return _clamp(score)

def _finish(result):
    score = result.ai_likelihood
    distance = abs(score - 50)
    if result.remote_used and distance >= 25 and len(result.evidence) >= 2:
        result.confidence = "high"
    elif distance >= 18 and len(result.evidence) >= 2:
        result.confidence = "medium"
    else:
        result.confidence = "low"
    if score >= 75:
        result.decision = "likely_ai"
    elif score <= 25:
        result.decision = "likely_human"
    else:
        result.decision = "uncertain"
    result.ai_likelihood = round(_clamp(score), 1)
    return result

async def analyze_image_bytes(data, filename="image"):
    started = time.perf_counter()
    if not data or len(data) > MAX_BYTES:
        raise DetectorError(
            "image exceeds the %d MB detector limit" % (MAX_BYTES // (1024 * 1024))
        )
    try:
        with Image.open(io.BytesIO(data)) as im:
            im.verify()
    except Exception as exc:
        raise DetectorError("unsupported or corrupted image") from exc

    result = DetectionResult("image")
    result.stages.append("metadata")
    meta, strong = await asyncio.to_thread(inspect_metadata, data, filename)
    result.evidence.extend(meta)
    if strong:
        result.ai_likelihood = 98.0
        result.stages.append("metadata_decisive")
        result.warnings.append(
            "A generator/provenance signature was found; signatures can be stripped or forged."
        )
        result.elapsed_ms = int((time.perf_counter() - started) * 1000)
        result.confidence = "high"
        result.decision = "likely_ai"
        return result

    result.stages.append("local_heuristics")
    local, ev = await asyncio.to_thread(image_heuristics, data)
    result.evidence.extend(ev)
    result.ai_likelihood = _fuse(local)

    if LOW < result.ai_likelihood < HIGH:
        result.stages.append("local_onnx")
        onnx_score = await asyncio.to_thread(local_onnx_image, data)
        if onnx_score is not None:
            result.ai_likelihood = _fuse(local, onnx_score)
            result.evidence.append(Evidence(
                "onnx",
                "Local CPU ONNX detector score: %.1f%% AI-like." % onnx_score,
                40,
                onnx_score,
            ))
        if LOW < result.ai_likelihood < HIGH:
            result.stages.append("free_hf_inference")
            remote = await remote_image(data)
            if remote:
                result.ai_likelihood = _fuse(local, remote[0])
                result.evidence.append(Evidence("remote", remote[1], 55, remote[0]))
                result.remote_used = True
            else:
                result.warnings.append(
                    "Free external inference was unavailable or rate-limited; local evidence only."
                )
    result.warnings.append("No AI signature does not prove human origin.")
    result.elapsed_ms = int((time.perf_counter() - started) * 1000)
    return _finish(result)

async def analyze_audio_bytes(data, filename="voice.ogg"):
    started = time.perf_counter()
    if not data or len(data) > MAX_BYTES:
        raise DetectorError(
            "voice clip exceeds the %d MB detector limit" % (MAX_BYTES // (1024 * 1024))
        )
    result = DetectionResult("audio")
    result.stages.append("metadata")
    meta, strong = await asyncio.to_thread(inspect_metadata, data, filename)
    result.evidence.extend(meta)
    if strong:
        result.ai_likelihood = 98.0
        result.stages.append("metadata_decisive")
        result.warnings.append(
            "A generator/provenance signature was found; signatures can be stripped or forged."
        )
        result.elapsed_ms = int((time.perf_counter() - started) * 1000)
        result.confidence = "high"
        result.decision = "likely_ai"
        return result

    result.stages.append("local_heuristics")
    local, ev, wav = await asyncio.to_thread(audio_heuristics, data)
    result.evidence.extend(ev)
    result.ai_likelihood = _fuse(local)

    if LOW < result.ai_likelihood < HIGH:
        result.stages.append("local_onnx")
        onnx_score = await asyncio.to_thread(local_onnx_audio, wav)
        if onnx_score is not None:
            result.ai_likelihood = _fuse(local, onnx_score)
            result.evidence.append(Evidence(
                "onnx",
                "Local CPU ONNX voice detector score: %.1f%% AI-like." % onnx_score,
                40,
                onnx_score,
            ))
        if LOW < result.ai_likelihood < HIGH:
            result.stages.append("free_hf_inference")
            remote = await remote_audio(wav)
            if remote:
                result.ai_likelihood = _fuse(local, remote[0])
                result.evidence.append(Evidence("remote", remote[1], 55, remote[0]))
                result.remote_used = True
            else:
                result.warnings.append(
                    "Free external inference was unavailable or rate-limited; local evidence only."
                )
    result.warnings.append(
        "Voice detectors are sensitive to codec, microphone, language and post-processing."
    )
    result.elapsed_ms = int((time.perf_counter() - started) * 1000)
    return _finish(result)

def format_detection_result(result):
    icon = {
        "likely_ai": "🤖",
        "likely_human": "🧑",
        "uncertain": "❓",
    }[result.decision]
    lines = [
        "%s <b>AI Media Check</b>" % icon,
        "AI likelihood: <b>%.0f%%</b>" % result.ai_likelihood,
        "Confidence: <b>%s</b>" % result.confidence,
        "Result: <b>%s</b>" % result.decision.replace("_", " "),
        "",
        "<b>Evidence</b>",
    ]
    for item in result.evidence[:6]:
        lines.append("• " + item.message)
    if result.warnings:
        lines.append("")
        lines.append("<b>Important</b>")
        for warning in result.warnings[:3]:
            lines.append("• " + warning)
    lines.append(
        "\n⏱ %d ms • %s" % (result.elapsed_ms, " → ".join(result.stages))
    )
    return "\n".join(lines)
